export const authConstants = {
    CHECK_CURRENT_SESSION_REQUEST: 'CHECK_CURRENT_SESSION_REQUEST',
    CHECK_CURRENT_SESSION_SUCCESS: 'CHECK_CURRENT_SESSION_SUCCESS',
    CHECK_CURRENT_SESSION_FAILURE: 'CHECK_CURRENT_SESSION_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
 
    LOGOUT: 'LOGOUT',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    RESEND_SIGNUP_REQUEST: 'RESEND_SIGNUP_REQUEST',
    RESEND_SIGNUP_SUCCESS: 'RESEND_SIGNUP_SUCCESS',
    RESEND_SIGNUP_FAILURE: 'RESEND_SIGNUP_FAILURE',

    EMAIL_CONFIRMATION_REQUEST: 'EMAIL_CONFIRMATION_REQUEST',
    EMAIL_CONFIRMATION_SUCCESS: 'EMAIL_CONFIRMATION_SUCCESS',
    EMAIL_CONFIRMATION_FAILURE: 'EMAIL_CONFIRMATION_FAILURE',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
    
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

    CHANGE_EMAIL_REQUEST: 'CHANGE_EMAIL_REQUEST',
    CHANGE_EMAIL_SUCCESS: 'CHANGE_EMAIL_SUCCESS',
    CHANGE_EMAIL_FAILURE: 'CHANGE_EMAIL_FAILURE',

    RESEND_CHANGE_EMAIL_REQUEST: 'RESEND_CHANGE_EMAIL_REQUEST',
    RESEND_CHANGE_EMAIL_SUCCESS: 'RESEND_CHANGE_EMAIL_SUCCESS',
    RESEND_CHANGE_EMAIL_FAILURE: 'RESEND_CHANGE_EMAIL_FAILURE',

    CHANGE_EMAIL_CONFIRMATION_REQUEST: 'CHANGE_EMAIL_CONFIRMATION_REQUEST',
    CHANGE_EMAIL_CONFIRMATION_SUCCESS: 'CHANGE_EMAIL_CONFIRMATION_SUCCESS',
    CHANGE_EMAIL_CONFIRMATION_FAILURE: 'CHANGE_EMAIL_CONFIRMATION_FAILURE',
};